<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=400 height=100></p>

Этот ноутбук посвящён основам  библиотеки PyTorch.

<h3 style="text-align: center;"><b>Введение</b></h3>

На текущее время было реализовано несколько различный фреймворков глубокого обучения. Разница между ними заключается во внутренних принципах вычислений. Например, в **[Caffe](http://caffe.berkeleyvision.org/)** и **[Caffe2](https://caffe2.ai/)** вы пишете код, используя некоторые «готовые блоки» (как и LEGO). На данный момент это уже история, сейчас **Caffe** стал частью **PyTorch**. 
В **[TensorFlow](https://www.tensorflow.org/)** вы сначала объявляете граф вычислений, затем компилируйте его и используйте для вывода / обучения (`tf.session ()`). Кстати, теперь в TensorFlow (начиная с версии 1.10) есть функция [Eager Execution](https://www.tensorflow.org/guide/eager), которая может быть полезна для быстрого прототипирования и отладки. **[Keras](https://keras.io/)** - очень популярный и полезный фреймворк DL, который позволяет быстро реализовывать нейронный сети и имеет множество полезных функций.


<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Image credit: https://habr.com/post/334380/</i><p>

Мы будем использовать **PyTorch**, поскольку он активно развивается и поддерживается AI-сообществом 

<h3 style="text-align: center;"><b>Установка</b></h3>

Подробную инструкцию по установке PyTorch вы можете найти на [официальном сайте PyTorch](https://pytorch.org/).

## Синтаксис Фреймворка

Несколько фактов о PyTorch:
- динамический граф вычислений
- удобные модули `torch.nn` и `torchvision` для быстрого прототипирования нейронных сетей
- даже быстрее, чем TensorFlow на некоторых задачах
- позволяет легко использовать **GPU**

По своей сути PyTorch предоставляет две основные функции:

- n-мерный тензор, похожий на **numpy**, но может работать на графических процессорах
- Автоматическая дифференциация для построения и обучения нейронных сетей

Если бы PyTorch был формулой, она была бы такой:

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Давайте посмотрим, как мы можем использовать PyTorch для работы с векторами и тензорами.

Напомним, что **тензор** - это многомерный вектор, например :

`x = np.array ([1,2,3])` - вектор = тензор с 1 размерностью (точнее: `(3,)`)

`y = np.array ([[1, 2, 3], [4, 5, 6]])` - матрица = тензор с двумя измерениями (`(2, 3)` в данном случае)

`z = np.array ([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) `-" куб "(3, 3, 3) = тензор с тремя измерениями (` ( 3, 3, 3) `в этом случае)


Одним из реальных примеров трехмерного тензора является **изображение**, оно имеет 3 измерения: `высота`, `ширина` и `глубина канала` (глубина канала = 3 для цветных изображений, 1 для оттенков серого). Вы можете думать об этом как о параллелепипеде, состоящем из действительных чисел.


### Типы Тензоров

В PyTorch мы будем использовать `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) для всех вычислений.

Все типы:

In [3]:
import torch

In [2]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

### Создание тензора

In [3]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [34]:
a.shape

torch.Size([2])

In [4]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
b.shape

torch.Size([2, 3])

### Инициализации тензоров

Инициализация случайного распределения

In [6]:
x = torch.randn((2,3))                # Normal(0, 1) с размером (2, 3)
x

tensor([[ 0.0166,  0.2257, -1.1230],
        [ 0.0571,  1.0262, -0.4169]])

In [7]:
print(x.random_(0, 10))                      # Дискретное равномерно U[0, 10]
print(x.uniform_(0, 1))                      # Равномерно U[0, 1]
print(x.normal_(mean=0, std=1))              # Нормальное со средним 0 и дисперсией 1
print(x.bernoulli_(p=0.5))                   # bernoulli with parameter p

tensor([[4., 9., 4.],
        [0., 2., 0.]])
tensor([[0.7242, 0.9746, 0.6340],
        [0.2592, 0.5168, 0.1877]])
tensor([[ 0.5550, -1.5075, -1.0807],
        [ 0.8684, -1.2007,  0.7106]])
tensor([[1., 0., 0.],
        [1., 1., 1.]])


## Функции в Torch 

У всех функций Numpy есть своя пара в Torch.

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

### Изменение формы
`np.reshape()` == `torch.view()`:

In [8]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

**Примечание:** `torch.view ()` создает новый тензор, но старый остается неизменным

In [10]:
b.view(-1, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [11]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Изменение типа тензора

In [12]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [13]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

In [14]:
a.to(torch.uint8)

tensor([  1,   3, 249], dtype=torch.uint8)

### Индексация

In [15]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [47]:
a[0, 0]

tensor(100.)

In [48]:
a[0:2, 1]

tensor([ 20., 163.])

### Арифметические операции

| операция | аналоги |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

#### Сложение

In [16]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [17]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [51]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

#### Вычитание

In [52]:
a - b

tensor([[ 2.,  4.,  6.],
        [20., 40., 60.],
        [ 0.,  0.,  0.]])

In [53]:
a.sub(b) 

tensor([[ 2.,  4.,  6.],
        [20., 40., 60.],
        [ 0.,  0.,  0.]])

#### Умножение (поэлементное)

In [54]:
a * b

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [ 1.0000e+04,  4.0000e+04,  9.0000e+04]])

In [55]:
a.mul(b)

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [ 1.0000e+04,  4.0000e+04,  9.0000e+04]])

#### Деление (поэлементное):

In [56]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [57]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

In [58]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Примечание:** все эти операции создают новые тензоры, старые тензоры остаются неизменными.

In [59]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [60]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

### Операторы сравнения

In [61]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [62]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [63]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [64]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [65]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

### Использование индексации по логической маске

In [66]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [67]:
b[a == b]

tensor([100., 200., 300.])

### Поэлементное применение **универсальных функций**

In [18]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [19]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [70]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [71]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [72]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

## Матричные операции

#### Транспонирование тензора

In [73]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [74]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

#### Скалярное произведение векторов

In [75]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [76]:
a.dot(b)

tensor(-141.)

#### Матричное произведение

In [77]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [78]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [79]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

## Конвертация
#### Конвертация из Numpy в Pytorch:

In [20]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.57725025, 0.38841153, 0.28398944],
       [0.51189432, 0.979944  , 0.89673677],
       [0.60720765, 0.53821333, 0.27560186]])

In [21]:
b = torch.from_numpy(a)
b

tensor([[0.5773, 0.3884, 0.2840],
        [0.5119, 0.9799, 0.8967],
        [0.6072, 0.5382, 0.2756]], dtype=torch.float64)

#### Конвертация из Torch в Numpy

In [22]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[-1.7625e-18,  1.2542e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [23]:
type(a)

torch.Tensor

In [24]:
x = a.numpy()
x

array([[[-1.7624837e-18,  1.2541621e-42,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]],
      dtype=float32)

In [25]:
x.shape

(2, 3, 4)

In [26]:
type(x)

numpy.ndarray

## <h1 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

CUDA --- это программно-аппаратная архитектура параллельных вычислений, которая позволяет существенно увеличить вычислительную производительность благодаря использованию графических процессоров фирмы Nvidia. Для нас CUDA --- это драйвер, который позволяет нам проводить вычисления на GPU.

[CUDA documentation](https://docs.nvidia.com/cuda/)

Для вычислений на Pytorch мы можем использовать как CPU (Central Processing Unit), так и GPU (Graphical Processing Unit). Между ними можно легко переключаться, и это очень важно!

#### Кладём тензор на GPU

In [4]:
x = torch.randn(1000, 1000, 100)

In [5]:
!nvidia-smi

Tue Jan 20 17:32:21 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   52C    P8            N/A  / 5001W |     468MiB /   4096MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
x = x.cuda()

In [12]:
x

tensor([[[-5.8748e-01,  7.0819e-01,  4.5043e-01,  ..., -9.0795e-02,
           3.4991e-01,  1.1828e+00],
         [-9.9108e-01,  5.0235e-02, -2.3041e+00,  ..., -8.2295e-01,
          -1.1115e+00,  1.0113e+00],
         [-2.2897e-01, -7.2032e-01,  2.2579e+00,  ..., -4.4464e-01,
           6.6801e-01, -1.0666e+00],
         ...,
         [ 1.0750e+00,  2.4464e-01,  8.7498e-01,  ...,  1.0784e+00,
           3.6565e-01,  4.5294e-01],
         [ 1.4828e-01,  7.2352e-01, -1.2748e-01,  ...,  4.8981e-01,
           4.8760e-01, -8.9123e-01],
         [ 1.5781e+00,  1.0356e+00,  2.5018e-03,  ..., -2.6688e-01,
           5.6545e-01, -2.1505e+00]],

        [[-1.0813e+00, -8.3038e-02,  4.8988e-01,  ...,  5.6689e-01,
          -1.1969e-01,  1.1345e+00],
         [ 1.1501e+00, -8.1253e-01, -2.9374e-01,  ...,  3.5994e-01,
          -1.2430e-01, -3.9590e-01],
         [-4.4743e-01,  3.1583e-01, -7.9393e-01,  ..., -3.3476e-01,
           8.6273e-01, -4.8262e-01],
         ...,
         [ 1.2515e+00, -3

In [13]:
!nvidia-smi

Tue Jan 20 17:32:57 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   51C    P5            N/A  / 5001W |     899MiB /   4096MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [9]:
x = x.cpu()

In [14]:
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")

x = x.to(device)
x

tensor([[[-5.8748e-01,  7.0819e-01,  4.5043e-01,  ..., -9.0795e-02,
           3.4991e-01,  1.1828e+00],
         [-9.9108e-01,  5.0235e-02, -2.3041e+00,  ..., -8.2295e-01,
          -1.1115e+00,  1.0113e+00],
         [-2.2897e-01, -7.2032e-01,  2.2579e+00,  ..., -4.4464e-01,
           6.6801e-01, -1.0666e+00],
         ...,
         [ 1.0750e+00,  2.4464e-01,  8.7498e-01,  ...,  1.0784e+00,
           3.6565e-01,  4.5294e-01],
         [ 1.4828e-01,  7.2352e-01, -1.2748e-01,  ...,  4.8981e-01,
           4.8760e-01, -8.9123e-01],
         [ 1.5781e+00,  1.0356e+00,  2.5018e-03,  ..., -2.6688e-01,
           5.6545e-01, -2.1505e+00]],

        [[-1.0813e+00, -8.3038e-02,  4.8988e-01,  ...,  5.6689e-01,
          -1.1969e-01,  1.1345e+00],
         [ 1.1501e+00, -8.1253e-01, -2.9374e-01,  ...,  3.5994e-01,
          -1.2430e-01, -3.9590e-01],
         [-4.4743e-01,  3.1583e-01, -7.9393e-01,  ..., -3.3476e-01,
           8.6273e-01, -4.8262e-01],
         ...,
         [ 1.2515e+00, -3

In [15]:
a = torch.randn(5,5).cuda()
b = torch.randn(5,5)

In [16]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!